### ISSUE TITLE
The first happy issue!

### ISSUE THREAD

**Issue by eugene-bright** [pedroelbanquero/TorahBibleCodes#3]
I glad you broke with the follower of the cult of Baal (mammon)

**Comment by pedroelbanquero** [comment]
HAHHAHA, well better here to talk everyone free

**Comment by eugene-bright** [comment]
Yeah, I like hells. The hells are the product of true freedom

**Comment by eugene-bright** [comment]
Now it's time to adopt the ways of love and combine it with the wisdom of hells: this way we will help only to those who ask. And others will be devoured by the tide

**Comment by pedroelbanquero** [comment]
i was looking the work of Dr Hoys  from pre historic monuments in europe, more ancients than hebrew than have same patterns or characters in many cases than proto hebrew or phoenician .

this dolmens are of tartesos, ancient advanced culture with phonetic alphabet

![image](https://user-images.githubusercontent.com/60758685/211796129-e9107ce4-ab4b-4996-9e04-f429958e2966.png)

the language and ibero language is not decrypted yet and is clearly  ancient hebrew

https://www.prehistoriadelsur.com/search/label/Trigueros

symbols are ancient symbols, and stars also .

**Comment by pedroelbanquero** [comment]
this culture use same way to make female and male words described in Raziel book, and names seems triplets like in sefer yetzira, and same number aprox of symbols and no aeiou , entropy of shanon 4.3 like hebrew language

**Comment by pedroelbanquero** [comment]
i think maybe we can set ancient symbols and make equivalences of gematria values of both cultures like in the book of kircher

and by this way find words, in common, word that cultures share

**Comment by eugene-bright** [comment]
This info mostly of historical value. It doesn't help to restore Hebrew-based quantum computing. For that reason I also abandoned Sanskrit (I have no means for recovering it).
But the Old Testament is mostly intact and of immense value. The New Revelation of the Lord Jesus Christ gives the insights into the work. And this work has been done already, I can feel it

**Comment by eugene-bright** [comment]
Rev. 19:14 And the armies in heaven, clothed in fine linen, white and clean, followed Him on white horses.
![IMG_20230111_134403_601](https://user-images.githubusercontent.com/39331266/211799165-8598b930-3299-4ff3-be20-8d543c979de9.jpg)

**Comment by pedroelbanquero** [comment]
> This info mostly of historical value. It doesn't help to restore Hebrew-based quantum computing. For that reason I also abandoned Sanskrit (I have no means for recovering it). But the Old Testament is mostly intact and of immense value. The New Revelation of the Lord Jesus Christ gives the insights into the work. And this work has been done already, I can feel it

not just historical, if hebrew can come from 7 000 ac
maybe text talks of something interesting
language have same patterns

**Comment by eugene-bright** [comment]
Hebrew came from the alternative future, from eternity, from true God. It's a limited version of the Universal language, humans are capable of grasping

**Comment by pedroelbanquero** [comment]
i agree , reason because alphabets are really important, because are the pieces to make cirtuits in the brains . and this is ancient hebrew not decryted yet

**Comment by eugene-bright** [comment]
Hebrew is the most advanced hyper-associative language we have nowadays. One have to become synesthetic to read it properly

**Comment by eugene-bright** [comment]
Show grace to fallen and.. stay apart from them

**Comment by pedroelbanquero** [comment]
take a look what you can read from stars from raziel and abraham encoding

https://github.com/pedroelbanquero/torahcodespython/issues/4

**Comment by eugene-bright** [comment]
The Confederation of Planets in the Service of the Infinite Creator has only one important statement. That statement, my friends, as you know, is “All things, all of life, all of the creation is part of one original thought.”
https://www.lawofone.info/s/1#0

**Comment by bartman081523** [comment]
https://www.encyclopedia.com/science/encyclopedias-almanacs-transcripts-and-maps/elkins-donald-t-1930-1984

https://www.amazon.com.au/Extraterrestrial-Communication-Telepathy-Data-Elkins/dp/1258770873

https://www.llresearch.org/
